name: skiff
version: 0.2.0
description: >-
  A lightweight, Future-based library for expressing CQRS principles in Dart
  projects.
homepage: https://github.com/thisdarktao/skiff
environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  test: ^1.17.10
  meta: ^1.7.0
  lints: ^1.0.1
